apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: ethereum-miner
  namespace: ethereum
spec:
  selector:
    matchLabels:
      app: ethereum-miner
  replicas: 1
  template:
    metadata:
      labels:
        app: ethereum-miner
    spec:
      containers:
      - name: ethereum-minernode
        imagePullPolicy: Always
        image: "kmgreen2/ethereum-miner:latest"
        resources:
          requests:
            memory: "256Mi"
            cpu: "0.1"
        ports:
        - containerPort: 30301
          name: server
        - containerPort: 8101
          name: rpc
        command:
        - sh
        - -c
        - "/start_miner.sh"
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - "nc -z -v -w5 localhost 30301 && nc -z -v -w5 localhost 8101"
          initialDelaySeconds: 10
          timeoutSeconds: 5
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - "nc -z -v -w5 localhost 30301 && nc -z -v -w5 localhost 8101"
          initialDelaySeconds: 10
          timeoutSeconds: 5
        volumeMounts:
        - name: logdir
          mountPath: /var/log/ethereum
      securityContext:
        fsGroup: 1000
      volumes:
        - name: logdir
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: ethereum-miner
  namespace: ethereum
  labels:
    app: ethereum-miner
spec:
  ports:
  - port: 30301
    name: client
  - port: 8101
    name: rpc
  selector:
    app: ethereum-miner
  clusterIP: None
